AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: Application Dollar Monitoring'
Resources:
  BillingRecordsSnsTopic:
    Type: 'AWS::SNS::Topic'
  LineItemPublish:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handlers/line-item-publisher.handler
      CodeUri: /Users/tom/Source/serverlessops/aws-adm/.serverless/aws-adm.zip
      Description: Ingest an S3 object and publish line items.
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          LOG_LEVEL: INFO
          AWS_SNS_TOPIC:
            Ref: BillingRecordsSnsTopic
          SCHEMA_CHANGE_HANDLING:
            Ref: SchemaChangeHandling
      Events:
        Event1:
          Type: S3
          Properties:
            Bucket:
              Ref: BillingReportBucket
            Events: 's3:ObjectCreated:Put'
            Filter:
              - suffix: .gz
Outputs:
  BillingRecordsSnsTopicArn:
    Description: SNS topic ARN where billing records are published to.
    Value:
      Ref: BillingRecordsSnsTopic
    Export:
      Name: aws-adm-prime-BillingRecordsSnsTopicArn
Parameters:
  SchemaChangeHandling:
    Type: String
    Description: Behavior by LineItemPublish function on report schema change.
    Default: CONTINUE
  BillingReportBucket:
    Type: String
    Description: Name of S3 bucket AWS Cost and Usage reports are delivered to.
    Default: ''
