AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: Application Cost Monitoring'
Resources:
  BillingRecordsSnsTopic:
    Type: 'AWS::SNS::Topic'
  Publish:
    Type: 'AWS::Serverless::Function'
    Properties:
      # NOTE: Necessary to handle LambdaInvokePolicy for self.
      FunctionName: 'aws-serverless-repository-ApplicationCostMonitoring-Publish'
      Runtime: python3.6
      Handler: handlers/line-item-publisher.handler
      CodeUri: s3://%%S3_BUCKET%%/%%S3_DEPLOY_ARTIFACT%%
      Description: Ingest an S3 object and publish line items.
      MemorySize: 512
      Timeout: 300
      Policies:
        - S3CrudPolicy:
            # NOTE: Need to ref the parameter to avoid a circular dependency.
            BucketName:
              Ref: BillingReportBucketName
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::GetAtt:
                - BillingRecordsSnsTopic
                - Arn
        - LambdaInvokePolicy:
            # NOTE: We can't Ref Stack name when publishing to AppRepo
            FunctionName: 'aws-serverless-repository-ApplicationCostMonitoring-Publish'
      Environment:
        Variables:
          LOG_LEVEL: INFO
          AWS_SNS_TOPIC:
            Ref: BillingRecordsSnsTopic
          SCHEMA_CHANGE_HANDLING:
            Ref: SchemaChangeHandling
      Events:
        Event1:
          Type: S3
          Properties:
            Bucket:
              Ref: BillingReportS3Bucket
            Events: 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .gz
        Event2:
          Type: S3
          Properties:
            Bucket:
              Ref: BillingReportS3Bucket
            Events: 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .zip
  BillingReportS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        Ref: BillingReportBucketName
Outputs:
  BillingReportS3BucketName:
    Description: Name of S3 Bucket for billing reports.
    Value:
      Ref: BillingReportS3Bucket
    Export:
      Name: aws-serverless-repository-ApplicationCostMonitoring-BillingReportS3BucketName
  BillingRecordsSnsTopicArn:
    Description: SNS topic ARN where billing records are published to.
    Value:
      Ref: BillingRecordsSnsTopic
    Export:
      Name: aws-serverless-repository-ApplicationCostMonitoring-BillingRecordsSnsTopicArn
Parameters:
  SchemaChangeHandling:
    Type: String
    Description: Behavior by Publish function on report schema change.
    Default: CONTINUE
  BillingReportBucketName:
    Type: String
    Description: Name of S3 bucket AWS Cost and Usage reports are delivered to.
