AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: Application Dollar Monitoring'
Resources:
  BillingRecordsSnsTopic:
    Type: 'AWS::SNS::Topic'
  LineItemPublish:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handlers/line-item-publisher.handler
      CodeUri: s3://%%S3_BUCKET%%/%%S3_DEPLOY_ARTIFACT%%
      Description: Ingest an S3 object and publish line items.
      MemorySize: 512
      Timeout: 300
      Policies:
        # FIXME: We need S3 delete
        - S3CrudPolicy:
            bucketName:
              Ref: AdmStateS3Bucket
        - SNSPublishMessagePolicy:
            topicName:
              Ref: BillingRecordsSnsTopic
        - LambdaInvokePolicy:
            functionName:
              Ref: LineItemPublish
      Environment:
        Variables:
          LOG_LEVEL: INFO
          AWS_SNS_TOPIC:
            Ref: BillingRecordsSnsTopic
          SCHEMA_CHANGE_HANDLING:
            Ref: SchemaChangeHandling
      Events:
        Event1:
          Type: S3
          Properties:
            Bucket: 'aws-adm-prime-billing-reports-#{AWS::AccountId}'
            Events: 's3:ObjectCreated:Put'
            Filter:
              - suffix: .gz
        Event2:
          Type: S3
          Properties:
            Bucket: 'aws-adm-prime-billing-reports-#{AWS::AccountId}'
            Events: 's3:ObjectCreated:Put'
            Filter:
              - suffix: .zip
Outputs:
  BillingRecordsSnsTopicArn:
    Description: SNS topic ARN where billing records are published to.
    Value:
      Ref: BillingRecordsSnsTopic
    Export:
      Name: aws-adm-prime-BillingRecordsSnsTopicArn
Parameters:
  SchemaChangeHandling:
    Type: String
    Description: Behavior by LineItemPublish function on report schema change.
    Default: CONTINUE
  BillingReportBucket:
    Type: String
    Description: Name of S3 bucket AWS Cost and Usage reports are delivered to.
    Default: ''
